### ISSUE TITLE
Not working with Smart Select

### ISSUE THREAD

**Issue by tinyCoder32** [valnub/Framework7-Upscroller-Plugin#8]
Hi, thanks for the awesome plugin!

The scroll button appears at the top of smart select that opens in popup, but it doesn't work.

![screen shot 2017-04-03 at 02 56 53](https://cloud.githubusercontent.com/assets/17817239/24592100/34b4ea08-1819-11e7-8210-161a0dfa3894.png)

**Comment by valnub** [comment]
Hi, can you post a reproducible example on codepen or jsfiddle so I can debug the issue? Thanks :)

**Comment by tinyCoder32** [comment]
Hi Timo, here is a jsfiddle: https://jsfiddle.net/tinyCoder32/L7cpjuvq/

I don't know why the up scroller even don't show up like in my real app. In my app it does appear at the top of the smart select window (while it should be hidden beneath it), and doesn't work when I click it.

Thanks!

**Comment by valnub** [comment]
Hi @tinyCoder32, thanks!
I'll try to look into it this weekend.

Cheers,
Timo

**Comment by tinyCoder32** [comment]
@valnub it seems like `var curpage = $$(".page-content", app.getCurrentView().activePage.container);` is taking the background page view not the `popup.page-content` view!

**Comment by tinyCoder32** [comment]
I replaced it with `var curpage = document.querySelectorAll(".page-content:nth-last-of-type(1)");` and it is working now! but smooth scrolling not working for popups, only on pages.

Hope you can give a better fix soon Timo.

Thanks.

**Comment by valnub** [comment]
@tinyCoder32 As you already pointed out, the Upscroller feature only works for the document itself, not smart select. It has never been designed to work within a popup layer. Fixing this means quite some extra work, as it is more a feature-request rather than a bug.

I recommend to rather think about why you need this feature? "Normal" native apps do not have this feature, so I think your problem rather comes from a coneptual/design issue than a technical problem.

**Comment by tinyCoder32** [comment]
But how to disable it on smart select! I don't want it! but it is showing!

**Comment by valnub** [comment]
@tinyCoder32 I don't see it in your fiddle
